### ISSUE TITLE
Bug in delimiter escaping eg. in AggressionBased<Dictionary<string,string>>

### ISSUE THREAD

**Issue by Leszek-Kowalski** [nemesissoft/Nemesis.TextParsers#1]
There seems to be a bug in escaping of delimiters in values of AggressionBased<Dictionary<string,string>>.

Unit tests attached on a branch

**Comment by MichalBrylka** [comment]
@Leszek-Kowalski 
I'm just pushing test restructure in 9c55345. Let's discuss potential implications and expectations tomorrow over the phone.  

Please consider parsing various possibilities upon parsing from:
`Key=Text\;Text`
Possible parsing types might include, Dictionary<string, string> (Dss), AggBas<Dss>, AggBas<AggBas<Dss>> etc

AggBas<Dss> can safely be parsed from
``Key=Text\\;Text``

Hot tip - use R# upon opening this project. From now on comments like "GH #1" will point to github

**Comment by MichalBrylka** [comment]
for consideration
We want ["Key#"] = "Va#lu#e" dictionary

from convenient form 
Key#=Va#lu#e
we get this dictionary when parsing Dss

upon parsing of AggBas<string> we get no error but result is weird
When parsing AggBas<Dss> - there is no way we can devour that

**Comment by MichalBrylka** [comment]
@Leszek-Kowalski please rebase your bug branch and point your attention to
"GH #1 fix or remove" comment

**Comment by Leszek-Kowalski** [comment]
As discussed: closing the issue as there is no bug. Current escaping behavior is a consequence of preserving correctness while also allowing multi level type composition.
