### ISSUE TITLE
Q: Is it possible to parse CSV files with this library?

### ISSUE THREAD

**Issue by fubar-coder** [nemesissoft/Nemesis.TextParsers#15]
**Is your feature request related to a problem? Please describe.**

I found this library and I'm not sure if this library can be used to read CSV files. It seems that way, but I have difficulties to find documentation for features like custom escaping, quoting, null handling and optional values.

I also miss an example how a the serialization format looks like, given the serialization options.

**Describe the solution you'd like**

Updated documentation to get a better idea of CSV de-/serialization is supported.

**Describe alternatives you've considered**

Using a different library

**Additional context**

**Comment by MichalBrylka** [comment]
Hi, thanks for your interest in that library but it is designed to parse single configuration values based on its type. It might be used as an “ingredient” of CSV parser (escaping sequences, performant splitting and complex values parsers) but itself it’s not a CSV parser

**Comment by MichalBrylka** [comment]
Since there is no more interest, I'm closing the issue
